### ISSUE TITLE
Im seeking some orientation regarding the usage of ex_sqlean under termux

### ISSUE THREAD

**Issue by leorodriguesrj** [mindreframer/ex_sqlean#1]
Hello, I have noticed that this project currently does not provide binaries for EM_AARCH64. Is there a way for me to provide my own binaries? Because I cloned [sqlean](https://github.com/mindreframer/sqlean) and compiled it successfully (apparently).

**Comment by mindreframer** [comment]
@leorodriguesrj Hello, no, currently there are no options to provide your own binaries. But it seems to be a great idea to provide an configuration option to be able to point to a folder with binaries compiled for less popular architectures. I'll open an issue for this feature.

**Comment by mindreframer** [comment]
The issue: https://github.com/mindreframer/ex_sqlean/issues/2

**Comment by leorodriguesrj** [comment]
Great! Thank you!
